rule all:
    input:
        "data/interim/ratings.csv",
        "data/interim/books.csv",
        "data/interim/users.csv",


rule get_data:
    output:
        "data/raw/BX-Book-Ratings.csv",
        "data/raw/BX-Books.csv",
        "data/raw/BX-Users.csv",
    shell:
        "source src/data/get_data.sh"


rule clean_raw_data:
    input:
        "data/raw/BX-Book-Ratings.csv",
        "data/raw/BX-Books.csv",
        "data/raw/BX-Users.csv",
    output:
        "data/interim/ratings.csv",
        "data/interim/books.csv",
        "data/interim/users.csv",

    shell:
        "python src/data/preprocess_raw_data.py {input} {output}"
