services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./src/sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    depends_on:
      - db
  
# Use docker inspect <container name> to find IPAddress for login
# Admin panel: `localhost:8080`:
# * Network - *IP from server container*
# * Login - root
# * Password - pass  